### ISSUE TITLE
Error when executing from terminal

### ISSUE THREAD

**Issue by vinaysahuhbti** [nielsutrecht/jwt-angular-spring#3]
I have created build using maven clean package
now when i am executing it using java -jar ..... it is throwing exception as -
Exception in thread "main" org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:474)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
    at com.example.WebApplication.main(WebApplication.java:24)

**Comment by nielsutrecht** [comment]
Hi @vinaysahuhbti 

The new version now created a proper runnable jar again. You can build it with mvn clean install and the resulting jar can be ran with java -jar.
